### ISSUE TITLE
[Error] metadata-generation-failed

### ISSUE THREAD

**Issue by Animaly0** [PeARSearch/PeARS-federated#34]
When trying to install the requirements in federated and lite, I get this error that may be related to an error in compiling Cython file :
https://paaster.io/5J4K73XRb5mSP5rRI8x4s#E-jigPI29DffGTxNQFSKoGssryMxXPR6PqzvNlkJcF0

**Comment by minimalparts** [comment]
@Animaly0 thanks for the report. Which version of Python are you using?

**Comment by Animaly0** [comment]
currently using Python 3.11.2

**Comment by minimalparts** [comment]
Thank you. We will try to reproduce and get back to you as soon as we can!

**Comment by minimalparts** [comment]
I'm sorry about the late reply. I have attempted to reproduce the problem, but so far in vain. It works for me on python 3.11.2, in a virtual environment. Have you perhaps tried to install scikit-learn separately, with 'pip install scikit-learn'?

**Comment by Animaly0** [comment]
Don’t worry, so I restarted from scrath and it now works like a charm… Don’t know what I did, might be because I tried too hard to install it using fish instead of bash.

Sorry for the incovenience, I’ll continue the installation process now.
Closing the issue.
