### ISSUE TITLE
Create user account through CLI (to bypass the need of setup-ing mail)

### ISSUE THREAD

**Issue by Poslovitch** [PeARSearch/PeARS-federated#35]
I have a local installation of PeARS-federated, on which it seems I can create an account through the sign up form. However, this fails as I have left most of the `.env` file "as is" (as per the currently-available [`.env-template`](https://github.com/PeARSearch/PeARS-federated/blob/c89076dd0c5f4e134e2ff094d567c6aff7dc3a21/.env-template)), thus, with default placeholder values, due to not knowing which does what, and being unwilling to set-up a local mail server.

I would like to create a user account through the CLI as this would grant me the ability to try user-related features (especially the contribution to the index, as I couldn't find documentation on how to do it through the CLI and `flask pears` commands' "help texts" seem lacking).

This would be a command akin to Django's `createsuperuser` (see [documentation](https://docs.djangoproject.com/en/5.0/ref/django-admin/#django-admin-createsuperuser)): pass in a username, password and email and it would then create the user with those credentials.

**Comment by minimalparts** [comment]
@Poslovitch that's a very good point! I agree that a CLI version would make a lot of sense. Might you be feeling enthusiastic about taking this on? Otherwise, I'll put it on our todo list :)

And yeah... we need to document the CLI commands, that module is still rather messy...

**Comment by Poslovitch** [comment]
Sure. I'll work on that then.

**Comment by minimalparts** [comment]
Hello @Poslovitch ! I was wondering whether you'd had a chance to look into this, and if not, whether it would be okay for me to solve the issue. It turns out I now also need this feature :) Thank you!

**Comment by Poslovitch** [comment]
Working on it!

**Comment by minimalparts** [comment]
Fantastic! Thank you :)

**Comment by minimalparts** [comment]
Thank you very much @Poslovitch ! I'm closing this issue.
